<?php
require __DIR__ . '/lib/bootstrap.php';
require __DIR__ . '/lib/db.php';
require __DIR__ . '/lib/auth.php';
require __DIR__ . '/lib/queries.php';
require __DIR__ . '/lib/layout.php';
require __DIR__ . '/lib/assistant.php';   // assistant_enabled()
require_login();

global $CONFIG;
$enabled = assistant_enabled($CONFIG);

// Suggested starter questions (the chips). Plain prompts — the model decides which tools to call.
$starters = [
    'How much did we spend on dining last month?',
    "What's our net worth and how has it changed this year?",
    "What's our biggest recurring bill?",
    'Are we on track for retirement?',
    'What bills are due in the next two weeks?',
    'How is our investment portfolio doing?',
];

render_header('Assistant', 'assistant', ['narrow' => true]);
?>

<?php if (!$enabled): ?>
    <section class="card">
        <div class="block-head"><h2>Assistant not configured</h2></div>
        <p class="muted intro-note">
            The AI assistant answers questions about your finances in plain English by looking up
            your real data. To enable it, add an <strong>Anthropic API key</strong> to
            <code>lib/config.php</code> (the <code>anthropic.api_key</code> setting) — the same key
            the 401(k) photo importer uses. It runs on pay-as-you-go Anthropic credits (a few cents
            per question) and is read-only: it can look things up but never change anything.
        </p>
    </section>
<?php else: ?>
    <section class="card assistant-card">
        <p class="muted assistant-intro">
            Ask about your spending, budgets, bills, net worth, investments, retirement, and more.
            I look up your real data to answer — you'll see what I'm checking as I work — and I'm
            read-only, so I can't change anything.
        </p>

        <div id="assistant-thread" class="assistant-thread" aria-live="polite"></div>

        <div id="assistant-starters" class="assistant-starters">
            <?php foreach ($starters as $s): ?>
                <button type="button" class="starter-chip" data-q="<?= e($s) ?>"><?= e($s) ?></button>
            <?php endforeach; ?>
        </div>

        <form id="assistant-form" class="assistant-form" autocomplete="off">
            <textarea id="assistant-input" class="assistant-input" rows="1"
                      placeholder="Ask about your finances…"
                      aria-label="Ask the assistant" maxlength="6000"></textarea>
            <button type="submit" id="assistant-send" class="btn assistant-send" aria-label="Send">Ask</button>
        </form>
        <p class="muted assistant-disclaimer">
            Answers are generated by AI from your data and may be imperfect — double-check anything important.
        </p>
    </section>
<?php endif; ?>

<?php render_footer(); ?>
